default: &default
  adapter: postgis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  schema_search_path: public

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test
  host: <%= Rails.application.credentials.db.host %>
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>
  socket: <%= ENV.fetch("INSTANCE_UNIX_SOCKET") %>


production:
  <<: *default
  database: production
