default: &default
  adapter: postgis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  username: postgres
  password: <%= ENV.fetch("ROR_LOCAL_DB_PW") {} %>
  schema_search_path: public

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

staging:
  <<: *default
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>
  host: <%= Rails.application.credentials.db.host %>
  database: production
  
production:
  <<: *default
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>
  host: <%= Rails.application.credentials.db.host %>
  database: production
